services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/pb_data:/bin/pb_data

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/home/appuser
